// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evqquwppyefizdueldbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2cXF1d3BweWVmaXpkdWVsZGJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODI5MzYsImV4cCI6MjA1OTg1ODkzNn0.-YUlNKagxRXzyJAH8yZSAm-VkkXO2A5OTrWFwk5DxOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);